export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_CURRENT_PRODUCT = 'LOAD_CURRENT_PRODUCT';

export const SUBMIT_PRODUCT = 'SUBMIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
