export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_ORIGINS = 'SET_ORIGINS';
export const SET_PRODUCTS_PER_PAGE= 'SET_PRODUCTS_PER_PAGE';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';

export const FILTERS_CHANGE_ACTIONS = [SET_PRODUCTS_PER_PAGE, SET_PRICE_RANGE, SET_ORIGINS, SET_PAGE_NUMBER];
