export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_ORIGINS = 'SET_ORIGINS';
export const SET_PRODUCTS_PER_PAGE= 'SET_PRODUCTS_PER_PAGE';

