export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_ORDER = 'ADD_ORDER';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_CURRENT_PRODUCT = 'LOAD_CURRENT_PRODUCT';

export const SUBMIT_PRODUCT = 'SUBMIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_ORIGINS = 'SET_ORIGINS';
export const SET_PRODUCTS_PER_PAGE= 'SET_PRODUCTS_PER_PAGE';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_EDITABLE = 'SET_EDITABLE';
export const LOAD_ORIGINS = 'LOAD_ORIGINS';

export const SET_TOTAL_NUMBER_OF_PAGES = 'SET_TOTAL_NUMBER_OF_PAGE';
export const SET_TOTAL_NUMBER_OF_PRODUCTS = 'SET_TOTAL_NUMBER_OF_PRODUCTS';

export const SET_ALL_ORDERS = 'SET_ALL_ORDERS';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const LOAD_DATA = 'LOAD_DATA';

export const CREATE_MY_PRODUCT = 'CREATE_MY_PRODUCT';
export const EDIT_MY_PRODUCT = 'EDIT_MY_PRODUCT';
export const DELETE_MY_PRODUCT = 'DELETE_MY_PRODUCT';
